version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: todoapp
    volumes:
      - .:/app
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - pg-dev-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: $DEV_USERNAME
      POSTGRES_DB: $DEV_NAME
      POSTGRES_PASSWORD: $DEV_PASSWORD

volumes:
  pg-dev-data: