name: CI/CD Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate-code:
    name: Code validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint || exit 1  

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: []
    env:
      TEST_DB_URL: ${{ secrets.TEST_DB_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: |
          npm test || exit 1

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd www/Todo-Manager
            echo "Current directory: $(pwd)"
            git pull origin master
            git status
            npm install --only=prod || exit 1

  notify-discord:
    name: Notify Discord
    runs-on: ubuntu-latest
    needs: [validate-code,test,deploy]
    if: always()
    steps:
      - name: Notify on success
        if: success()
        uses: Ilshidur/action-discord@master
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: 'Workflow completed successfully.'

      - name: Notify on failure
        if: failure()
        uses: Ilshidur/action-discord@master
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: 'Workflow failed. Check the workflow logs for details.'
